spring:
  ai:
    mcp:
      client:
        type: ASYNC
        sse:
          connections:
            webflux-mcp-server:
              url: http://localhost:8080
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-2024-08-06
#          model: gpt-4.1-nano-2025-04-14
#          model: gpt-4.1-mini-2025-04-14
#          model: gpt-4o-mini-2024-07-18
server:
  port: 8081